"""Locale JSON 形状校验门禁（Batch-3 H13）。

``resolve()`` / ``t()`` 合约要求 locale 是「对象树 + 字符串叶子」；
坏数据进 main 后 Batch-2 H11 只能在 call-time warn 已经太晚——本脚本
lint-time 就挡回 PR。i18next/polyglot/formatjs 都有同款校验。

合约：
  * 默认扫 ``static/locales/`` + ``packages/vscode/locales/``；
  * ``--locales-dir`` 自定义 dir（本测试用它避开真实 bundle）；
  * 递归：叶子必须是 ``str``，interior 必须是 ``dict``；数字/布尔/null/数组皆违规；
  * 空 dict 合法（namespace 占位）；
  * 干净 → exit 0；违规 → exit 1 + ``path › key.path :: reason`` stderr；
  * 对 ``_pseudo/pseudo.json`` 同样生效。
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "check_i18n_locale_shape.py"


def _python() -> str:
    """沿用当前解释器，让 ruff / uv 管理的 venv 路径可复现。"""
    return sys.executable


def _run(args: list[str], cwd: Path | None = None) -> tuple[int, str, str]:
    env = os.environ.copy()
    env.setdefault("PYTHONPATH", str(ROOT))
    proc = subprocess.run(
        [_python(), str(SCRIPT), *args],
        capture_output=True,
        text=True,
        timeout=15,
        check=False,
        cwd=str(cwd) if cwd else None,
        env=env,
    )
    return proc.returncode, proc.stdout, proc.stderr


def _write_bundle(base: Path, name: str, payload: dict) -> Path:
    base.mkdir(parents=True, exist_ok=True)
    path = base / f"{name}.json"
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return path


@unittest.skipUnless(SCRIPT.exists() or True, "script is generated by this batch")
class TestLocaleShapeScript(unittest.TestCase):
    """针对 validator 本体的独立 pin；真实 locales 由下方单独测覆盖。"""

    def setUp(self) -> None:
        self._tmp = tempfile.mkdtemp(prefix="aiia-locale-shape-")
        self.addCleanup(shutil.rmtree, self._tmp, ignore_errors=True)
        self.root = Path(self._tmp)

    def _run_against(
        self, payload: dict, *, filename: str = "en"
    ) -> tuple[int, str, str]:
        _write_bundle(self.root, filename, payload)
        return _run(["--locales-dir", str(self.root)])

    # happy path
    def test_script_exists_and_is_executable(self) -> None:
        self.assertTrue(SCRIPT.exists(), f"missing script: {SCRIPT}")

    def test_exit_zero_for_valid_tree(self) -> None:
        code, _, err = self._run_against(
            {
                "page": {
                    "title": "AI Intervention Agent",
                    "submit": "Send",
                },
                "errors": {
                    "network": "Failed to reach server.",
                    "nested": {"retry": "Retry"},
                },
                "empty_namespace": {},
            }
        )
        self.assertEqual(code, 0, err)

    # 坏叶子类型
    def test_exit_nonzero_when_leaf_is_number(self) -> None:
        code, _, err = self._run_against({"page": {"count": 3}})
        self.assertNotEqual(code, 0)
        self.assertIn("page.count", err)
        self.assertIn("number", err.lower())

    def test_exit_nonzero_when_leaf_is_bool(self) -> None:
        code, _, err = self._run_against({"flags": {"enabled": True}})
        self.assertNotEqual(code, 0)
        self.assertIn("flags.enabled", err)

    def test_exit_nonzero_when_leaf_is_null(self) -> None:
        code, _, err = self._run_against({"page": {"title": None}})
        self.assertNotEqual(code, 0)
        self.assertIn("page.title", err)

    def test_exit_nonzero_when_leaf_is_array(self) -> None:
        code, _, err = self._run_against({"page": {"items": ["a", "b"]}})
        self.assertNotEqual(code, 0)
        self.assertIn("page.items", err)

    # 坏 interior 类型
    def test_exit_nonzero_when_interior_is_array(self) -> None:
        code, _, err = self._run_against({"page": [1, 2]})
        self.assertNotEqual(code, 0)
        self.assertIn("page", err)

    def test_exit_nonzero_on_invalid_json(self) -> None:
        path = self.root / "en.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("{not-valid-json", encoding="utf-8")
        code, _, err = _run(["--locales-dir", str(self.root)])
        self.assertNotEqual(code, 0)
        self.assertIn("en.json", err)

    # 跨文件聚合
    def test_aggregates_errors_across_multiple_files(self) -> None:
        _write_bundle(self.root, "en", {"page": {"count": 3}})
        _write_bundle(self.root, "zh-CN", {"page": {"flag": True}})
        code, _, err = _run(["--locales-dir", str(self.root)])
        self.assertNotEqual(code, 0)
        self.assertIn("en.json", err)
        self.assertIn("zh-CN.json", err)

    # pseudo locale 也是普通 json → 同规则生效
    def test_pseudo_locale_same_rules_apply(self) -> None:
        nested = self.root / "_pseudo"
        _write_bundle(nested, "pseudo", {"page": {"count": 0}})
        code, _, err = _run(["--locales-dir", str(self.root)])
        self.assertNotEqual(code, 0)
        self.assertIn("pseudo.json", err)

    # --help 提示
    def test_help_flag_prints_usage(self) -> None:
        code, out, _ = _run(["--help"])
        self.assertEqual(code, 0)
        self.assertIn("locale", out.lower())


class TestLocaleShapeAgainstRealBundles(unittest.TestCase):
    """端到端：生产 locale bundle 必须形状干净，否则 ci_gate 失败。"""

    def test_static_locales_are_clean(self) -> None:
        target = ROOT / "static" / "locales"
        code, _, err = _run(["--locales-dir", str(target)])
        self.assertEqual(code, 0, err)

    def test_vscode_locales_are_clean(self) -> None:
        target = ROOT / "packages" / "vscode" / "locales"
        code, _, err = _run(["--locales-dir", str(target)])
        self.assertEqual(code, 0, err)


if __name__ == "__main__":
    unittest.main()
