"""Locale JSON shape validation gate (Batch-3 H13).

Why this matters
----------------
Our ``resolve()`` / ``t()`` contract assumes locale JSONs are
**tree-of-objects with string leaves**. Everything else is a bug:
numbers, booleans, arrays and nulls silently leak into the UI as
``[object Object]`` or the empty string, and the non-string-resolve
warning (Batch-2 H11) only fires at call-time — too late if the bad
data lands on ``main``.

The i18next team's ``i18next-resources-to-backend`` and Formatjs'
``extract`` scripts both run a lint pass that refuses to emit a
bundle when the shape is wrong. Airbnb's ``polyglot.js`` ships
``Polyglot.validate`` for the same reason. Batch-3 H13 ports that
pattern as ``scripts/check_i18n_locale_shape.py`` and wires it into
``ci_gate.py`` so a reviewer can't merge ``{"count": 3}`` into a
locale bundle.

Contract
--------
* ``scripts/check_i18n_locale_shape.py`` scans ``static/locales/`` and
  ``packages/vscode/locales/`` by default.
* ``--locales-dir`` flag accepts a custom dir (used by these tests
  so CI doesn't need to mutate the real locale bundle).
* Walk recursively: every leaf **must** be a ``str``; every
  interior node **must** be a ``dict``. Lists, numbers, booleans,
  ``null`` and non-string leaves are errors.
* Empty dicts are allowed (namespace placeholder).
* Exit 0 on clean tree, 1 on any violation. Prints a structured
  ``path › key.path :: reason`` diagnostic to stderr.
* Works on the pseudo-locale bundle (``_pseudo/pseudo.json``) with
  the same rules.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "check_i18n_locale_shape.py"


def _python() -> str:
    """Use the same interpreter the tests run under so virtualenvs
    with ruff/uv-managed python resolve deterministically."""
    return sys.executable


def _run(args: list[str], cwd: Path | None = None) -> tuple[int, str, str]:
    env = os.environ.copy()
    env.setdefault("PYTHONPATH", str(ROOT))
    proc = subprocess.run(
        [_python(), str(SCRIPT), *args],
        capture_output=True,
        text=True,
        timeout=15,
        check=False,
        cwd=str(cwd) if cwd else None,
        env=env,
    )
    return proc.returncode, proc.stdout, proc.stderr


def _write_bundle(base: Path, name: str, payload: dict) -> Path:
    base.mkdir(parents=True, exist_ok=True)
    path = base / f"{name}.json"
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return path


@unittest.skipUnless(SCRIPT.exists() or True, "script is generated by this batch")
class TestLocaleShapeScript(unittest.TestCase):
    """Stand-alone pin of the validator. The real locales are scanned
    from a separate test below."""

    def setUp(self) -> None:
        self._tmp = tempfile.mkdtemp(prefix="aiia-locale-shape-")
        self.addCleanup(shutil.rmtree, self._tmp, ignore_errors=True)
        self.root = Path(self._tmp)

    def _run_against(
        self, payload: dict, *, filename: str = "en"
    ) -> tuple[int, str, str]:
        _write_bundle(self.root, filename, payload)
        return _run(["--locales-dir", str(self.root)])

    # ------------------------------------------------------------------
    # happy path
    # ------------------------------------------------------------------
    def test_script_exists_and_is_executable(self) -> None:
        self.assertTrue(SCRIPT.exists(), f"missing script: {SCRIPT}")

    def test_exit_zero_for_valid_tree(self) -> None:
        code, _, err = self._run_against(
            {
                "page": {
                    "title": "AI Intervention Agent",
                    "submit": "Send",
                },
                "errors": {
                    "network": "Failed to reach server.",
                    "nested": {"retry": "Retry"},
                },
                "empty_namespace": {},
            }
        )
        self.assertEqual(code, 0, err)

    # ------------------------------------------------------------------
    # bad leaf types
    # ------------------------------------------------------------------
    def test_exit_nonzero_when_leaf_is_number(self) -> None:
        code, _, err = self._run_against({"page": {"count": 3}})
        self.assertNotEqual(code, 0)
        self.assertIn("page.count", err)
        self.assertIn("number", err.lower())

    def test_exit_nonzero_when_leaf_is_bool(self) -> None:
        code, _, err = self._run_against({"flags": {"enabled": True}})
        self.assertNotEqual(code, 0)
        self.assertIn("flags.enabled", err)

    def test_exit_nonzero_when_leaf_is_null(self) -> None:
        code, _, err = self._run_against({"page": {"title": None}})
        self.assertNotEqual(code, 0)
        self.assertIn("page.title", err)

    def test_exit_nonzero_when_leaf_is_array(self) -> None:
        code, _, err = self._run_against({"page": {"items": ["a", "b"]}})
        self.assertNotEqual(code, 0)
        self.assertIn("page.items", err)

    # ------------------------------------------------------------------
    # bad interior types
    # ------------------------------------------------------------------
    def test_exit_nonzero_when_interior_is_array(self) -> None:
        code, _, err = self._run_against({"page": [1, 2]})
        self.assertNotEqual(code, 0)
        self.assertIn("page", err)

    def test_exit_nonzero_on_invalid_json(self) -> None:
        path = self.root / "en.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("{not-valid-json", encoding="utf-8")
        code, _, err = _run(["--locales-dir", str(self.root)])
        self.assertNotEqual(code, 0)
        self.assertIn("en.json", err)

    # ------------------------------------------------------------------
    # aggregates across multiple files
    # ------------------------------------------------------------------
    def test_aggregates_errors_across_multiple_files(self) -> None:
        _write_bundle(self.root, "en", {"page": {"count": 3}})
        _write_bundle(self.root, "zh-CN", {"page": {"flag": True}})
        code, _, err = _run(["--locales-dir", str(self.root)])
        self.assertNotEqual(code, 0)
        self.assertIn("en.json", err)
        self.assertIn("zh-CN.json", err)

    # ------------------------------------------------------------------
    # pseudo-locale is just another json file → still guarded
    # ------------------------------------------------------------------
    def test_pseudo_locale_same_rules_apply(self) -> None:
        nested = self.root / "_pseudo"
        _write_bundle(nested, "pseudo", {"page": {"count": 0}})
        code, _, err = _run(["--locales-dir", str(self.root)])
        self.assertNotEqual(code, 0)
        self.assertIn("pseudo.json", err)

    # ------------------------------------------------------------------
    # --help surface
    # ------------------------------------------------------------------
    def test_help_flag_prints_usage(self) -> None:
        code, out, _ = _run(["--help"])
        self.assertEqual(code, 0)
        self.assertIn("locale", out.lower())


class TestLocaleShapeAgainstRealBundles(unittest.TestCase):
    """End-to-end: the real production locale bundles must already be
    shape-clean once H13 is implemented, otherwise ci_gate turns red."""

    def test_static_locales_are_clean(self) -> None:
        target = ROOT / "static" / "locales"
        code, _, err = _run(["--locales-dir", str(target)])
        self.assertEqual(code, 0, err)

    def test_vscode_locales_are_clean(self) -> None:
        target = ROOT / "packages" / "vscode" / "locales"
        code, _, err = _run(["--locales-dir", str(target)])
        self.assertEqual(code, 0, err)


if __name__ == "__main__":
    unittest.main()
