// AUTO-GENERATED by scripts/gen_i18n_types.py — do not edit by hand.
// Run `python scripts/gen_i18n_types.py` to regenerate after
// editing packages/vscode/locales/en.json.

export type I18nKey =
  | "aiia.state.empty.message.default"
  | "aiia.state.empty.message.filtered"
  | "aiia.state.empty.title"
  | "aiia.state.error.action.copy_diagnostics"
  | "aiia.state.error.action.open_log"
  | "aiia.state.error.action.retry"
  | "aiia.state.error.message.network"
  | "aiia.state.error.message.server_500"
  | "aiia.state.error.message.timeout"
  | "aiia.state.error.message.unknown"
  | "aiia.state.error.title"
  | "aiia.state.loading.message"
  | "aiia.state.loading.title"
  | "notify.hint.loadFailedHttp"
  | "notify.hint.requestTimeout"
  | "notify.hint.serverUrlMissing"
  | "settings.autoSave"
  | "settings.autoSaveTooltip"
  | "settings.bark.action"
  | "settings.bark.actionCopy"
  | "settings.bark.actionNone"
  | "settings.bark.actionUrl"
  | "settings.bark.deviceKey"
  | "settings.bark.deviceKeyPlaceholder"
  | "settings.bark.enabled"
  | "settings.bark.icon"
  | "settings.bark.iconPlaceholder"
  | "settings.bark.url"
  | "settings.bark.urlPlaceholder"
  | "settings.close"
  | "settings.config.path"
  | "settings.config.pathPlaceholder"
  | "settings.config.title"
  | "settings.enabled"
  | "settings.feedback.countdown"
  | "settings.feedback.countdownHint"
  | "settings.feedback.promptSuffix"
  | "settings.feedback.promptSuffixPlaceholder"
  | "settings.feedback.resubmitPrompt"
  | "settings.feedback.resubmitPromptPlaceholder"
  | "settings.feedback.saveFailed"
  | "settings.feedback.saved"
  | "settings.feedback.title"
  | "settings.footer.github"
  | "settings.footer.version"
  | "settings.hint.barkTestSent"
  | "settings.hint.coreNotReady"
  | "settings.hint.loadFailed"
  | "settings.hint.loadFailedReason"
  | "settings.hint.loading"
  | "settings.hint.macosNotEnabled"
  | "settings.hint.macosTestTriggered"
  | "settings.hint.noChange"
  | "settings.hint.notifyDisabled"
  | "settings.hint.postFailed"
  | "settings.hint.remoteChanged"
  | "settings.hint.syncFailed"
  | "settings.hint.syncFailedHttp"
  | "settings.hint.syncFailedNoUrl"
  | "settings.hint.synced"
  | "settings.hint.syncing"
  | "settings.hint.testFailed"
  | "settings.hint.testFailedHttp"
  | "settings.hint.testFailedNoUrl"
  | "settings.hint.testing"
  | "settings.hint.timeout"
  | "settings.macosNative"
  | "settings.test.macosMessage"
  | "settings.test.macosTitle"
  | "settings.testBark"
  | "settings.testNative"
  | "settings.title"
  | "statusBar.clickToOpen"
  | "statusBar.connected"
  | "statusBar.disconnected"
  | "statusBar.language"
  | "statusBar.openSettings"
  | "statusBar.reason"
  | "statusBar.tasks"
  | "statusBar.unknown"
  | "ui.clipboard.empty"
  | "ui.clipboard.insertFailed"
  | "ui.clipboard.inserted"
  | "ui.clipboard.noCode"
  | "ui.connecting"
  | "ui.copy.failed"
  | "ui.copy.label"
  | "ui.copy.success"
  | "ui.countdown.remaining"
  | "ui.form.insertCode"
  | "ui.form.optionsLabel"
  | "ui.form.placeholder"
  | "ui.form.submit"
  | "ui.form.uploadImage"
  | "ui.image.decodeFailed"
  | "ui.image.invalid"
  | "ui.image.processingFailedReason"
  | "ui.image.readFailed"
  | "ui.image.tooLarge"
  | "ui.image.tooManyFiles"
  | "ui.image.unsupportedFormat"
  | "ui.noContent.connecting"
  | "ui.noContent.title"
  | "ui.noContent.waiting"
  | "ui.notification.newTask"
  | "ui.notification.newTasks"
  | "ui.notification.taskCountSuffix"
  | "ui.notification.title"
  | "ui.settingsBtn"
  | "ui.settingsPanel.loadFailed"
  | "ui.settingsPanel.openFailed"
  | "ui.settingsPanel.unavailable"
  | "ui.status.connected"
  | "ui.status.disconnected"
  | "ui.status.disconnectedRetrying"
  | "ui.status.serverConnected"
  | "ui.status.serverDisconnected"
  | "ui.status.serverStatus"
  | "ui.submit.failed"
  | "ui.submit.failedReason"
  | "ui.submit.label"
  | "ui.submit.rateLimitHint"
  | "ui.submit.rateLimited"
  | "ui.submit.rateLimited429"
  | "ui.submit.submitting"
  | "ui.submit.success"
  | "ui.submit.timeoutCheckServer"
  | "ui.task.activateTimeoutCheckServer"
  | "ui.task.switchFailed"
  | "ui.task.switchedTo"
  | "ui.toast.configFallback"
  | "ui.toast.configFallbackReason"

export const I18N_KEYS: readonly I18nKey[] = [
  "aiia.state.empty.message.default",
  "aiia.state.empty.message.filtered",
  "aiia.state.empty.title",
  "aiia.state.error.action.copy_diagnostics",
  "aiia.state.error.action.open_log",
  "aiia.state.error.action.retry",
  "aiia.state.error.message.network",
  "aiia.state.error.message.server_500",
  "aiia.state.error.message.timeout",
  "aiia.state.error.message.unknown",
  "aiia.state.error.title",
  "aiia.state.loading.message",
  "aiia.state.loading.title",
  "notify.hint.loadFailedHttp",
  "notify.hint.requestTimeout",
  "notify.hint.serverUrlMissing",
  "settings.autoSave",
  "settings.autoSaveTooltip",
  "settings.bark.action",
  "settings.bark.actionCopy",
  "settings.bark.actionNone",
  "settings.bark.actionUrl",
  "settings.bark.deviceKey",
  "settings.bark.deviceKeyPlaceholder",
  "settings.bark.enabled",
  "settings.bark.icon",
  "settings.bark.iconPlaceholder",
  "settings.bark.url",
  "settings.bark.urlPlaceholder",
  "settings.close",
  "settings.config.path",
  "settings.config.pathPlaceholder",
  "settings.config.title",
  "settings.enabled",
  "settings.feedback.countdown",
  "settings.feedback.countdownHint",
  "settings.feedback.promptSuffix",
  "settings.feedback.promptSuffixPlaceholder",
  "settings.feedback.resubmitPrompt",
  "settings.feedback.resubmitPromptPlaceholder",
  "settings.feedback.saveFailed",
  "settings.feedback.saved",
  "settings.feedback.title",
  "settings.footer.github",
  "settings.footer.version",
  "settings.hint.barkTestSent",
  "settings.hint.coreNotReady",
  "settings.hint.loadFailed",
  "settings.hint.loadFailedReason",
  "settings.hint.loading",
  "settings.hint.macosNotEnabled",
  "settings.hint.macosTestTriggered",
  "settings.hint.noChange",
  "settings.hint.notifyDisabled",
  "settings.hint.postFailed",
  "settings.hint.remoteChanged",
  "settings.hint.syncFailed",
  "settings.hint.syncFailedHttp",
  "settings.hint.syncFailedNoUrl",
  "settings.hint.synced",
  "settings.hint.syncing",
  "settings.hint.testFailed",
  "settings.hint.testFailedHttp",
  "settings.hint.testFailedNoUrl",
  "settings.hint.testing",
  "settings.hint.timeout",
  "settings.macosNative",
  "settings.test.macosMessage",
  "settings.test.macosTitle",
  "settings.testBark",
  "settings.testNative",
  "settings.title",
  "statusBar.clickToOpen",
  "statusBar.connected",
  "statusBar.disconnected",
  "statusBar.language",
  "statusBar.openSettings",
  "statusBar.reason",
  "statusBar.tasks",
  "statusBar.unknown",
  "ui.clipboard.empty",
  "ui.clipboard.insertFailed",
  "ui.clipboard.inserted",
  "ui.clipboard.noCode",
  "ui.connecting",
  "ui.copy.failed",
  "ui.copy.label",
  "ui.copy.success",
  "ui.countdown.remaining",
  "ui.form.insertCode",
  "ui.form.optionsLabel",
  "ui.form.placeholder",
  "ui.form.submit",
  "ui.form.uploadImage",
  "ui.image.decodeFailed",
  "ui.image.invalid",
  "ui.image.processingFailedReason",
  "ui.image.readFailed",
  "ui.image.tooLarge",
  "ui.image.tooManyFiles",
  "ui.image.unsupportedFormat",
  "ui.noContent.connecting",
  "ui.noContent.title",
  "ui.noContent.waiting",
  "ui.notification.newTask",
  "ui.notification.newTasks",
  "ui.notification.taskCountSuffix",
  "ui.notification.title",
  "ui.settingsBtn",
  "ui.settingsPanel.loadFailed",
  "ui.settingsPanel.openFailed",
  "ui.settingsPanel.unavailable",
  "ui.status.connected",
  "ui.status.disconnected",
  "ui.status.disconnectedRetrying",
  "ui.status.serverConnected",
  "ui.status.serverDisconnected",
  "ui.status.serverStatus",
  "ui.submit.failed",
  "ui.submit.failedReason",
  "ui.submit.label",
  "ui.submit.rateLimitHint",
  "ui.submit.rateLimited",
  "ui.submit.rateLimited429",
  "ui.submit.submitting",
  "ui.submit.success",
  "ui.submit.timeoutCheckServer",
  "ui.task.activateTimeoutCheckServer",
  "ui.task.switchFailed",
  "ui.task.switchedTo",
  "ui.toast.configFallback",
  "ui.toast.configFallbackReason",
] as const
