#!/usr/bin/env python3
"""CI 门禁：禁止前端 JS 源文件里出现硬编码的中文/日文/韩文字符串字面量。

背景
----
Web UI 的前端代码全部通过 i18n key + locale JSON 提供用户可见文本。为了让
locale 成为唯一真源、方便未来扩展更多语言，我们约束 JS 源文件里不出现
中文/日文/韩文字符（CJK Unified Ideographs、Hiragana、Katakana、Hangul）
的**字符串字面量**。注释里的 CJK 字符不受限制（它们是开发者文档）。

默认作用域是 Web UI（``static/js/*``）。VSCode webview（``packages/vscode/*``）
目前不在本门禁范围内——它会在 P8 阶段单独处理。当 VSCode webview 完成 i18n
清理后，只需把 ``--scope all`` 改为默认即可收口。

实现细节
--------
- 扫描 ``static/js/*.js`` 源文件（默认），或通过 ``--scope all`` 扩展到
  ``packages/vscode/*.js``。
- 忽略 ``.min.js`` 产物（由 minifier 从源文件派生）。
- 忽略 VSCode 侧的 ``dist/``、``test/``、``vendor/``、``mathjax/``、
  ``node_modules/`` 等非 webview 源文件。
- 使用轻量词法扫描：先把 ``/* */`` 块注释和 ``//`` 行注释替换成空白（保留行
  号），再匹配单引号、双引号、模板字符串字面量。
- 支持显式豁免：若某一行带有 ``// aiia:i18n-allow-cjk`` 注释，则本行上的
  CJK 字符串字面量会被跳过（用于极少数需要硬编码 CJK 的场景，如 AI prompt
  默认值）。请谨慎使用。

退出码
------
- 0：所有 JS 源文件不包含硬编码 CJK 字符串字面量。
- 1：至少有一个违反项；逐行输出位置与内容。
- 2：配置错误（``--scope`` 对应的某个 scan root 解析后指向不存在的
  目录）。R101 之前这条路径返回 0（silent skip），与 R76 重布局后
  R88/R100 修过的同款 silent-broken 风险一致；改为 fail-loud 让
  reviewer 立刻看到漂移。
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

_WEBUI_ROOT = ROOT / "src" / "ai_intervention_agent" / "static" / "js"
_VSCODE_ROOT = ROOT / "packages" / "vscode"

SCOPES: dict[str, tuple[Path, ...]] = {
    "webui": (_WEBUI_ROOT,),
    "vscode": (_VSCODE_ROOT,),
    "all": (_WEBUI_ROOT, _VSCODE_ROOT),
}

CJK_RE = re.compile(
    r"["
    r"\u4e00-\u9fff"  # CJK Unified Ideographs
    r"\u3040-\u309f"  # Hiragana
    r"\u30a0-\u30ff"  # Katakana
    r"\uac00-\ud7af"  # Hangul Syllables
    r"]"
)

STRING_RE = re.compile(
    # Negative lookbehind for backslash prevents a `\`` appearing inside a
    # regex literal (e.g. /`/g) or an already-escaped context from being
    # mistaken for a fresh template-literal opener — which could otherwise
    # pair up with a later backtick and report ghost CJK hits inside the
    # surrounding HTML template literal.
    r"(?<!\\)'([^'\\\n]*(?:\\.[^'\\\n]*)*)'"
    r"|(?<!\\)\"([^\"\\\n]*(?:\\.[^\"\\\n]*)*)\""
    r"|(?<!\\)`([^`\\]*(?:\\.[^`\\]*)*)`",
    re.DOTALL,
)

# R98：剥序由「先 block 后 line」改为「先 line 后 block」——和 R92
# (``check_i18n_orphan_keys.py`` / ``check_i18n_param_signatures.py``) 与
# R97 (``check_i18n_ts_no_cjk.py``) 的双层 bug 完全同源。R92 提交时漏 back-
# port 到 ``js_no_cjk``——这是同一族扫描器中最后一个仍带 buggy 实现的。
#
# 旧实现 bug
# ----------
# ``BLOCK_COMMENT_RE.sub`` 在前的话，line comment 内裸写的 ``/*`` 会被 block-
# comment 正则当成开头，吞噬到下一处真实 ``*/`` 为止。R92 docstring 已经
# 点名两个真实触发点：
#   - ``static/js/app.js:538``  (``// 走 locales/*.json 静态 key 且无参数``)
#     吞 509 行直到下一处 JSDoc ``*/``
#   - ``static/js/i18n.js:1013`` (``// 通道，值来自 locales/*.json...``)
#     吞 58 行直到下一处 ``*/``
# 这两段被吞区域**当前**都没有未豁免的硬编码 CJK 字面量（实测 0 silent
# miss），所以表面零误报，但属于「latent silent breakage」——任何未来 patch
# 在被吞区域插入 CJK 字面量都会逃过扫描。
#
# 为什么不用 token-level lex
# --------
# 与 R97 同样的 trade-off：完整识别 JS 5-token 需要解决 RegExp literal 的
# slash-ambiguity（``a/b/c`` 是除法 vs regex 取决于上下文），工程量大；R92
# 折中已被 sister scanners 在生产稳定运行多月，对当前代码库实测 0 误报。
#
# 已知 trade-off（与 R92/R97 一致）
# --------
# ``//`` 出现在 string 字面量内（如 ``"https://..."``）会被 line-strip 截
# 短，可能漏掉同字符串内的 CJK。实测 ``static/js/*.js`` + ``packages/vscode/
# *.js`` 中的此类 string 全是 ASCII URL（github.com / localhost），0 处含
# CJK，未来若出现「URL 含 CJK 域名」+「需要 i18n」的双重场景再升级。
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
ALLOW_MARKER = "aiia:i18n-allow-cjk"


def _strip_comments(src: str) -> str:
    """Zero out ``//`` line comments and ``/* ... */`` block comments while
    preserving line offsets exactly (``\\n`` count and total byte length
    unchanged) so that ``stripped[:start].count("\\n") + 1`` line-number
    mapping in callers stays accurate.

    Pass order matters (R98/R97/R92): line comments are blanked **before**
    block comments. Otherwise patterns like ``// see locales/*.json`` get
    mis-parsed because the bare ``/*`` inside the *line* comment is read as
    a block-comment opener that swallows hundreds of subsequent lines.
    """

    def _blank_block(match: re.Match[str]) -> str:
        span = match.group(0)
        return "".join("\n" if ch == "\n" else " " for ch in span)

    out_lines: list[str] = []
    for line in src.split("\n"):
        idx = line.find("//")
        out_lines.append(line if idx == -1 else line[:idx] + " " * (len(line) - idx))
    intermediate = "\n".join(out_lines)
    return BLOCK_COMMENT_RE.sub(_blank_block, intermediate)


# Directories under packages/vscode that contain non-webview code or vendored
# third-party assets – they must not be scanned:
#   - dist/       : compiled TS output (regenerated by build)
#   - test/       : VSCode extension host tests (Node side, legitimate CJK in
#                   describe/it blocks is acceptable; webview tests live in
#                   the top-level tests/ folder instead)
#   - vendor/     : vendored third-party JS
#   - mathjax/    : vendored MathJax bundle
#   - node_modules/, out/, .vscode-test/ : build / editor scratch dirs
_VSCODE_SKIP_PREFIXES: tuple[str, ...] = (
    "packages/vscode/dist/",
    "packages/vscode/test/",
    "packages/vscode/vendor/",
    "packages/vscode/mathjax/",
    "packages/vscode/node_modules/",
    "packages/vscode/out/",
    "packages/vscode/.vscode-test/",
)


def _iter_js_source_files(roots: tuple[Path, ...]) -> list[Path]:
    paths: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for path in sorted(root.rglob("*.js")):
            if path.name.endswith(".min.js"):
                continue
            rel = path.relative_to(ROOT).as_posix()
            if any(rel.startswith(prefix) for prefix in _VSCODE_SKIP_PREFIXES):
                continue
            paths.append(path)
    return paths


def _line_has_allow_marker(original_src: str, line_number: int) -> bool:
    lines = original_src.splitlines()
    if 1 <= line_number <= len(lines):
        return ALLOW_MARKER in lines[line_number - 1]
    return False


def scan_file(path: Path) -> list[tuple[int, str]]:
    """Return a list of (line_number, literal) violations for a given file.

    Race-safe: 如果 ``rglob`` 列出文件后, 文件被并行 pytest worker / VS Code
    监视器 / 临时文件 cleanup 删除 (典型 race window <50ms), 直接返回空列表
    而非 raise FileNotFoundError。这种 race 在 CI (pre-commit hook + lint
    并行执行) 与本地 xdist (-n 4) 都可能复现。本 invariant 关心的是 *真
    实存在的 source file 是否含 CJK*, 临时文件本来就不该被 scanner 捕获。
    """
    try:
        src = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return []
    stripped = _strip_comments(src)

    offenders: list[tuple[int, str]] = []
    for match in STRING_RE.finditer(stripped):
        literal = match.group(1) or match.group(2) or match.group(3) or ""
        if not CJK_RE.search(literal):
            continue
        start = match.start()
        line_number = stripped[:start].count("\n") + 1
        if _line_has_allow_marker(src, line_number):
            continue
        offenders.append((line_number, literal))
    return offenders


def collect_violations(scope: str) -> list[tuple[Path, int, str]]:
    roots = SCOPES[scope]
    offenders: list[tuple[Path, int, str]] = []
    for path in _iter_js_source_files(roots):
        for line, literal in scan_file(path):
            offenders.append((path, line, literal))
    return offenders


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--scope",
        choices=sorted(SCOPES.keys()),
        default="webui",
        help="扫描范围：webui=Web UI（默认，P7 已清理完毕）；"
        "vscode=VSCode webview（P8 待清理，暂不挂 CI）；"
        "all=两者合并。",
    )
    args = parser.parse_args(argv)

    # R101：path-drift sanity check —— scope 对应的所有 root 必须真实存
    # 在。``_iter_js_source_files`` 之前在 root 不存在时 ``continue`` 跳
    # 过此 root 继续扫剩下的，main() 看到 0 violations 然后 print "OK"——
    # silent skip 模式与 R76 重布局后 R88/R100/R101 修过的同款 silent-
    # broken 风险一致。``packages/vscode`` 是 VS Code extension 核心面，
    # ``static/js`` 是 Web UI 核心面，任一缺失都是配置漂移而非合法 skip。
    expected_roots = SCOPES[args.scope]
    missing = [r for r in expected_roots if not r.exists()]
    if missing:
        rels = [r.relative_to(ROOT).as_posix() for r in missing]
        print(
            f"ERROR: JS scan root(s) not found for scope={args.scope}: "
            f"{', '.join(rels)}\n"
            f"  Resolved absolute paths: {[str(p) for p in missing]}\n"
            f"  This is a configuration drift, not 'OK' — failing loud "
            f"(exit 2) instead of silently skipping (R101; matches R88/R100).",
            file=sys.stderr,
        )
        return 2

    violations = collect_violations(args.scope)
    for path, line, literal in violations:
        rel = path.relative_to(ROOT).as_posix()
        snippet = literal if len(literal) < 80 else literal[:77] + "..."
        print(f"{rel}:{line}: hardcoded CJK string literal: {snippet!r}")
    if violations:
        print(
            f"\nFound {len(violations)} hardcoded CJK string literal(s) in JS sources "
            f"(scope={args.scope}). Move user-visible text to locale JSON and use "
            f"t('...') instead, or tag the line with '// {ALLOW_MARKER}' if the "
            f"literal is deliberately hardcoded.",
            file=sys.stderr,
        )
        return 1
    print(f"OK: no hardcoded CJK string literals in JS sources (scope={args.scope})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
