#!/usr/bin/env python3
"""P9·L8 — generate a TypeScript literal-union type for every i18n
key shipped in ``packages/vscode/locales/en.json``.

Motivation
----------
We already have:

- **ESLint rule** ``aiia-i18n/no-missing-i18n-key`` — catches unknown
  keys in ``.js`` / ``.mjs``.
- **pytest** ``tests/test_i18n_used_keys_exist.py`` — catches unknown
  keys statically.

But ``packages/vscode/extension.ts`` is *TypeScript*, and the
``hostT(key: string)`` signature means a typo like
``hostT('statusBar.langugage')`` still compiles. We want:

```ts
hostT('statusBar.language')       // OK
hostT('statusBar.langugage')      // TS error: Argument of type ... is not assignable
hostT('does.not.exist')           // TS error
```

Approach
--------
Read the canonical ``packages/vscode/locales/en.json`` (the source of
truth for VSCode-side i18n), flatten every leaf string into a dotted
path, and emit a TypeScript declaration file:

```ts
// AUTO-GENERATED by scripts/gen_i18n_types.py — do not edit by hand.
export type I18nKey =
  | 'aiia.state.noContent.desc'
  | 'aiia.state.noContent.title'
  | ...
```

CI gate (``--check``) regenerates in-memory and diffs against the
committed file; drift = exit 1. Identical to how ``gen_pseudo_locale.py
--check`` guards ``_pseudo/pseudo.json`` parity.

Why not auto-generate from both ``static/locales`` AND
``packages/vscode/locales``?
   The only TypeScript file calling ``t()``-like helpers is
   ``packages/vscode/extension.ts``, which hits ``hostT`` sourcing from
   ``packages/vscode/locales``. Adding the web locales would introduce
   noise for keys that extension.ts can never legitimately use.
   The pytest-based orphan scanner keeps both sides in sync; ESLint
   already polices .js call sites.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EN_JSON = ROOT / "packages" / "vscode" / "locales" / "en.json"
OUT_DTS = ROOT / "packages" / "vscode" / "i18n-keys.d.ts"

BANNER = (
    "// AUTO-GENERATED by scripts/gen_i18n_types.py — do not edit by hand.\n"
    "// Run `python scripts/gen_i18n_types.py` to regenerate after\n"
    "// editing packages/vscode/locales/en.json.\n"
)


def _flatten(obj: dict, prefix: str = "") -> list[str]:
    """Flatten a nested locale JSON into dotted string paths."""
    out: list[str] = []
    for k, v in obj.items():
        full = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            out.extend(_flatten(v, full))
        elif isinstance(v, str):
            out.append(full)
    return out


def render_dts(keys: list[str]) -> str:
    """Produce the final ``.d.ts`` body.

    - Keys are sorted deterministically so git diffs stay minimal.
    - Each key is on its own line so merges stay readable.
    - We export BOTH the union type (``I18nKey``) and the full runtime
      array (``I18N_KEYS``) so callers that need the raw list for a
      dropdown UI don't have to write their own.
    """
    keys_sorted = sorted(set(keys))
    union_lines = "\n".join(f"  | {json.dumps(k)}" for k in keys_sorted)
    array_lines = ",\n".join(f"  {json.dumps(k)}" for k in keys_sorted)
    return (
        BANNER
        + "\n"
        + "export type I18nKey =\n"
        + union_lines
        + "\n\n"
        + "export const I18N_KEYS: readonly I18nKey[] = [\n"
        + array_lines
        + ",\n"
        + "] as const\n"
    )


def load_keys(src: Path) -> list[str]:
    raw = json.loads(src.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise SystemExit(f"expected dict at top level of {src}, got {type(raw)!r}")
    return _flatten(raw)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the committed .d.ts doesn't match regenerated output.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Write the generated .d.ts to stdout instead of a file.",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=EN_JSON,
        help=f"Source locale JSON (default: {EN_JSON.relative_to(ROOT)}).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT_DTS,
        help=f"Destination .d.ts (default: {OUT_DTS.relative_to(ROOT)}).",
    )
    args = parser.parse_args(argv)

    keys = load_keys(args.source)
    generated = render_dts(keys)

    if args.stdout:
        sys.stdout.write(generated)
        return 0

    if args.check:
        if not args.out.exists():
            print(
                f"[gen_i18n_types] missing {args.out.relative_to(ROOT)};"
                " run `python scripts/gen_i18n_types.py` to create it.",
                file=sys.stderr,
            )
            return 1
        current = args.out.read_text(encoding="utf-8")
        if current == generated:
            print(
                f"[gen_i18n_types] {args.out.relative_to(ROOT)} is up to date"
                f" ({len(keys)} keys).",
            )
            return 0
        print(
            f"[gen_i18n_types] {args.out.relative_to(ROOT)} is OUT OF DATE"
            f" ({len(keys)} keys in source). Run `python scripts/gen_i18n_types.py`.",
            file=sys.stderr,
        )
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(generated, encoding="utf-8")
    print(
        f"[gen_i18n_types] wrote {args.out.relative_to(ROOT)} ({len(keys)} keys).",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
